version: '2.4'
services:
  bot-sepolia:
    environment:
      - NODE_ENV=sepolia
    image: nft_bot
    build:
      context: .
      dockerfile: Dockerfile
    cpus: 1
    mem_limit: 1G
    command: node src/bot.js
    restart: unless-stopped
