version: '3.7'
volumes:
    data_leveragex-bot: { }
services:
    leveragex-bot:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        env_file: ".env"
        ports:
            - "4000"
        volumes:
            - data_leveragex-bot:/data/db
        networks:
            - default
networks:
    default:
        driver: bridge
